"""alteracao tabela owner

Revision ID: 6c23854ff2b3
Revises: 7973ce3febf3
Create Date: 2022-04-13 18:41:12.488694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c23854ff2b3'
down_revision = '7973ce3febf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('active', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owner', 'active')
    # ### end Alembic commands ###
