"""alteracao tabela manager

Revision ID: 7973ce3febf3
Revises: 2a037a7e0e63
Create Date: 2022-04-13 11:33:31.229605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7973ce3febf3'
down_revision = '2a037a7e0e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('active', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manager', 'active')
    # ### end Alembic commands ###
