"""initial tables

Revision ID: ff4f364fe6d1
Revises: 
Create Date: 2022-03-28 19:41:38.586084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4f364fe6d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postal_code',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('postal_code_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('postal_code_id'),
    sa.UniqueConstraint('city')
    )
    op.create_index(op.f('ix_postal_code_postal_code_id'), 'postal_code', ['postal_code_id'], unique=False)
    op.create_table('user',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=45), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=45), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=45), nullable=False),
    sa.Column('password_encoder', sa.Enum('bcrypt', 'scrypt', name='encoder'), nullable=False),
    sa.Column('password', sa.CHAR(length=60), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('nif', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('address',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('postal_code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('details', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['postal_code_id'], ['postal_code.postal_code_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_index(op.f('ix_address_address'), 'address', ['address'], unique=False)
    op.create_index(op.f('ix_address_user_id'), 'address', ['user_id'], unique=False)
    op.create_table('contact',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_type', sa.Enum('fax', 'movel', 'fixo', name='contacttype'), nullable=False),
    sa.Column('number', sa.VARCHAR(length=15), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_index(op.f('ix_contact_number'), 'contact', ['number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_number'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_address_user_id'), table_name='address')
    op.drop_index(op.f('ix_address_address'), table_name='address')
    op.drop_table('address')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_postal_code_postal_code_id'), table_name='postal_code')
    op.drop_table('postal_code')
    # ### end Alembic commands ###
